-- MySQL Script generated by MySQL Workbench
-- Sun Jul 17 02:33:41 2022
-- Model: gean Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gean
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gean
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gean` ;
USE `gean` ;

-- -----------------------------------------------------
-- Table `gean`.`diarista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`diarista` ;

CREATE TABLE IF NOT EXISTS `gean`.`diarista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gean`.`responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`responsavel` ;

CREATE TABLE IF NOT EXISTS `gean`.`responsavel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gean`.`residencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`residencia` ;

CREATE TABLE IF NOT EXISTS `gean`.`residencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` INT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `responsavel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_residencia_responsavel1_idx` (`responsavel_id` ASC),
  CONSTRAINT `fk_residencia_responsavel1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `gean`.`responsavel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gean`.`faxinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`faxinas` ;

CREATE TABLE IF NOT EXISTS `gean`.`faxinas` (
  `id` INT NOT NULL AUTO_INCREMENT primary key,
  `diarista_id` INT NOT NULL,
  `residencia_id` INT NOT NULL,
  `dt_agenda` DATETIME NULL,
  `preco` DECIMAL(9) NULL,
  `compareceu` INT NULL,
  `feedback` VARCHAR(255) NULL,
  INDEX `fk_faxinas_diarista1_idx` (`diarista_id` ASC),
  INDEX `fk_faxinas_residencia1_idx` (`residencia_id` ASC),
  CONSTRAINT `fk_faxinas_diarista1`
    FOREIGN KEY (`diarista_id`)
    REFERENCES `gean`.`diarista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faxinas_residencia1`
    FOREIGN KEY (`residencia_id`)
    REFERENCES `gean`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
