-- MySQL Script generated by MySQL Workbench
-- Sun Jul 17 02:33:41 2022
-- Model: gean Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gean
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gean
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gean` ;
USE `gean` ;

-- -----------------------------------------------------
-- Table `gean`.`diarista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`diarista` ;

CREATE TABLE IF NOT EXISTS `gean`.`diarista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;

INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Bruna", "04514406502");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Jéssica", "04514406505");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Paula", "04514406510");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Ana", "04514406511");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Laura", "04514406512");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Raquel", "04514406513");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Fernanda", "04514406514");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Clara", "04514406515");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Rebeca", "04514406516");
INSERT INTO gean.diarista (nome, cpf)
        VALUES ("Mariana", "04514406517");


-- -----------------------------------------------------
-- Table `gean`.`responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`responsavel` ;

CREATE TABLE IF NOT EXISTS `gean`.`responsavel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Lucas", "04514406501");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Fernando", "04514406502");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Joaquim", "04514406503");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Bruno", "04514406504");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Gabriel", "04514406505");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Guilherme", "04514406506");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Claudio", "04514406507");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Emanuel", "04514406508");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Ravi", "04514406509");
INSERT INTO gean.responsavel (nome, cpf)
        VALUES ("Gael", "04514406510");


-- -----------------------------------------------------
-- Table `gean`.`residencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`residencia` ;

CREATE TABLE IF NOT EXISTS `gean`.`residencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `numero` INT NULL,
  `tamanho` VARCHAR(45) NOT NULL,
  `responsavel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_residencia_responsavel1_idx` (`responsavel_id` ASC),
  CONSTRAINT `fk_residencia_responsavel1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `gean`.`responsavel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Igarassu", "Cruz de Rebouças", "Rua Frei Miguelinho", "Condominio", 299, "P", 1);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Abreu e Lima", "Matinha", "Rua 15 de novembro", "s/c", 220, "P", 1);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Barueri", "Pq. dos Camargos", "Rua Vera", "s/c", 320, "m", 2);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Jandira", "Gabriela", "Rua Safira", "s/c", 46, "m", 2);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Caconde", "Santa Cruz", "Rua Aimorés", "s/c", 245, "P", 3);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Jaguariúna", "Vargeão", "Avenida Pacifico Moneda", "Condominio", 2925, "p", 3);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Campinas", "Cambuí", "Rua 13 de maio", "s/c", 29, "g", 3);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Holambra", "Centro", "Rua Alameda Maurício de Nassau", "boxe comercial", 676, "m", 4);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Jaguariúna", "Centro", "Rua Silvia Bueno", "s/c", 780, "g", 5);
INSERT INTO gean.residencia (cidade, bairro, rua, complemento, numero, tamanho, responsavel_id)
        VALUES ("Jaguariúna", "Berlim", "Rua Alfredo Bueno", "Condominio", 112, "g", 5);


-- -----------------------------------------------------
-- Table `gean`.`faxinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gean`.`faxinas` ;

CREATE TABLE IF NOT EXISTS `gean`.`faxinas` (
  `id` INT NOT NULL AUTO_INCREMENT primary key,
  `diarista_id` INT NOT NULL,
  `residencia_id` INT NOT NULL,
  `dt_agenda` DATETIME NULL,
  `preco` DECIMAL(9) NULL,
  `compareceu` INT NULL,
  `feedback` VARCHAR(255) NULL,
  INDEX `fk_faxinas_diarista1_idx` (`diarista_id` ASC),
  INDEX `fk_faxinas_residencia1_idx` (`residencia_id` ASC),
  CONSTRAINT `fk_faxinas_diarista1`
    FOREIGN KEY (`diarista_id`)
    REFERENCES `gean`.`diarista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faxinas_residencia1`
    FOREIGN KEY (`residencia_id`)
    REFERENCES `gean`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (1, 1, now(), 100.00, 1, "Adorei");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (2, 2, now(), 100.00, 1, "Tabalho excelente");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (3, 3, now(), 200.00, 1, "Super dedicada, uma execelente profissional");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (4, 4, now(), 200.00, 1, "Recomendo");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (5, 5, now(), 100.00, 1, "Pontual, trabalhadora");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (6, 6, now(), 100.00, 1, "Melhor serviço da região");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (7, 7, now(), 300.00, 1, "Não tem medo do trabalho, super recomendo");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (8, 8, now(), 200.00, 1, "Preço, cuidado, carinho e super dedicada");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (9, 9, now(), 300.00, 1, "Amo seus serviços");
INSERT INTO gean.faxinas (diarista_id, residencia_id, dt_agenda, preco, compareceu, feedback)
        VALUES (10, 10, now(), 300.00, 0, "Contratei e não apareceu, não recomendo");




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
